// <auto-generated />
using System;
using Carbon_Vault.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carbon_Vault.Migrations
{
    [DbContext(typeof(Carbon_VaultContext))]
    partial class Carbon_VaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carbon_Vault.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 4, 0, 4, 51, 478, DateTimeKind.Utc).AddTicks(1455),
                            Email = "admin@carbonvault.com",
                            Name = "André Castanho",
                            Nif = "123456789",
                            Password = "43dOXTeDC+QuR5dKyIy1azOYISeVpCNtBfBa0w9oUrduFC7XDIg0wqvWNum/Z5HX",
                            Role = 1,
                            State = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 4, 0, 4, 51, 478, DateTimeKind.Utc).AddTicks(1463),
                            Email = "user1@carbonvault.com",
                            Name = "John Doe",
                            Nif = "987654321",
                            Password = "/mngqsnZKE4IJO7g42SBkIMCrN0NWbHLuFXfKOZ/gDAv+NrscFc7YN60L1fUIy61",
                            Role = 0,
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 4, 0, 4, 51, 478, DateTimeKind.Utc).AddTicks(1465),
                            Email = "support@carbonvault.com",
                            Name = "John Smith",
                            Nif = "333333333",
                            Password = "RHQ56eIrDxJjOV+eqmDbwBxL9Ns6pT6ZlMMAfxvrvMAVvrm2xNJjz/S2Nt1ZQFXi",
                            Role = 3,
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 3, 4, 0, 4, 51, 478, DateTimeKind.Utc).AddTicks(1467),
                            Email = "user2@carbonvault.com",
                            Name = "My User",
                            Nif = "444444444",
                            Password = "OEBf882OMVW+ZiqEc3xuVfkD4DqmhmvBfLq0Q8FFG8WnOgzPjcOHXlo51as8VWRq",
                            Role = 0,
                            State = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 3, 4, 0, 4, 51, 478, DateTimeKind.Utc).AddTicks(1468),
                            Email = "user3@carbonvault.com",
                            Name = "Jane Doe",
                            Nif = "555555555",
                            Password = "GRmlELYkjxUkvNzMawfcU352tc60DxQAbL2xK/GFPKH36k8zbOktstg/ossRBP42",
                            Role = 0,
                            State = 1
                        });
                });

            modelBuilder.Entity("Carbon_Vault.Models.CarbonCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CarbonCredits");
                });

            modelBuilder.Entity("Carbon_Vault.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CarbonCreditsGenerated")
                        .HasColumnType("float");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefits = "Access to clean water, improved health conditions.",
                            CarbonCreditsGenerated = 1000.0,
                            Certification = "ISO 14001",
                            Description = "Providing clean water access to rural communities.",
                            Developer = "Green Solutions",
                            EndDate = new DateTime(2026, 3, 4, 0, 4, 51, 478, DateTimeKind.Local).AddTicks(2088),
                            ImageUrl = "https://hub.jhu.edu/at-work/2020/01/15/focus-on-wellness-drinking-more-water/",
                            Location = "Africa",
                            Name = "Water Access Initiative",
                            PricePerCredit = 12.50m,
                            ProjectUrl = "https://example.com/project1",
                            StartDate = new DateTime(2024, 12, 4, 0, 4, 51, 478, DateTimeKind.Local).AddTicks(2021),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Benefits = "Sustainable energy solutions, reduced carbon emissions.",
                            CarbonCreditsGenerated = 2000.0,
                            Certification = "LEED Gold",
                            Description = "Solar energy projects to provide electricity to underserved areas.",
                            Developer = "Renewable Power Inc.",
                            EndDate = new DateTime(2027, 3, 4, 0, 4, 51, 478, DateTimeKind.Local).AddTicks(2214),
                            ImageUrl = "https://www.google.com/imgres?q=solar%20energy%20portugal&imgurl=https%3A%2F%2Fwww.edpr.com%2Fsites%2Fedpr%2Ffiles%2F2022-04%2FAlqueva%2520solar%2520flotante.jpg&imgrefurl=https%3A%2F%2Fwww.edpr.com%2Fpt-pt%2Fnoticias%2F2022%2F04%2F05%2Fedpr-obtem-direito-de-ligacao-a-rede-no-leilao-de-solar-flutuante-em-portugal-0&docid=uEba6PNQx25XkM&tbnid=yXMOjdpzWolGBM&vet=12ahUKEwi2loOxxe2LAxWURPEDHXgyNwgQM3oECGMQAA..i&w=1300&h=975&hcb=2&itg=1&ved=2ahUKEwi2loOxxe2LAxWURPEDHXgyNwgQM3oECGMQAA",
                            Location = "South America",
                            Name = "Solar Energy for All",
                            PricePerCredit = 15.75m,
                            ProjectUrl = "https://example.com/project2",
                            StartDate = new DateTime(2025, 2, 4, 0, 4, 51, 478, DateTimeKind.Local).AddTicks(2211),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Carbon_Vault.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Carbon_Vault.Models.UserEmissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("diesel")
                        .HasColumnType("float");

                    b.Property<double>("electricity")
                        .HasColumnType("float");

                    b.Property<double>("petrol")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserEmissions");
                });

            modelBuilder.Entity("ProjectProjectType", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.Property<int>("TypesId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsId", "TypesId");

                    b.HasIndex("TypesId");

                    b.ToTable("ProjectProjectType");
                });

            modelBuilder.Entity("Carbon_Vault.Models.CarbonCredit", b =>
                {
                    b.HasOne("Carbon_Vault.Models.Account", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carbon_Vault.Models.Project", "Project")
                        .WithMany("CarbonCredits")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectProjectType", b =>
                {
                    b.HasOne("Carbon_Vault.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carbon_Vault.Models.ProjectType", null)
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carbon_Vault.Models.Project", b =>
                {
                    b.Navigation("CarbonCredits");
                });
#pragma warning restore 612, 618
        }
    }
}
