name: Build and deploy Node.js app to Azure Web App - CarbonVaultClient

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd Carbon_Vault/Carbon_Vault_Angular/carbon_vault_angular.client
          npm install
          npm run build --if-present --verbose

      - name: Verify build output
        run: ls -R Carbon_Vault/Carbon_Vault_Angular/carbon_vault_angular.client/dist/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: Carbon_Vault/Carbon_Vault_Angular/carbon_vault_angular.client/dist/carbon_vault_angular.client/browser

      - name: Verify artifact upload
        run: ls -R Carbon_Vault/Carbon_Vault_Angular/carbon_vault_angular.client/dist/carbon_vault_angular.client/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./node-app

      - name: Verify artifact download
        run: ls -R ./node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CarbonVaultClient'
          slot-name: 'Production'
          package: ./node-app
